import { Inter } from "next/font/google";
import Script from 'next/script';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pantry Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <head>
          <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-70WJWJCY9K"
              strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-70WJWJCY9K');
            `}
          </Script>
        </head>
      <body className={inter.className}>{children}</body>
      </html>
  );
}
